#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Com.Loonytone.Droid.Banners.Resource", IsApplication=false)]

namespace Com.Loonytone.Droid.Banners
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public static int scale_with_alpha = 2130968576;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int delay_time = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public static int image_scale_type = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public static int indicator_drawable_selected = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int indicator_drawable_unselected = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int indicator_height = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int indicator_margin = 2130771977;
			
			// aapt resource value: 0x7f010007
			public static int indicator_width = 2130771975;
			
			// aapt resource value: 0x7f010002
			public static int is_auto_play = 2130771970;
			
			// aapt resource value: 0x7f01000c
			public static int layout_id = 2130771980;
			
			// aapt resource value: 0x7f010001
			public static int scroll_time = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int title_background = 2130771971;
			
			// aapt resource value: 0x7f010006
			public static int title_height = 2130771974;
			
			// aapt resource value: 0x7f010004
			public static int title_textcolor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int title_textsize = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int black_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int gray_radius = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int white_radius = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public static int bannerContainer = 2131034112;
			
			// aapt resource value: 0x7f050005
			public static int bannerTitle = 2131034117;
			
			// aapt resource value: 0x7f050001
			public static int bannerViewPager = 2131034113;
			
			// aapt resource value: 0x7f050008
			public static int center = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int center_crop = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public static int center_inside = 2131034122;
			
			// aapt resource value: 0x7f050002
			public static int circleIndicator = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public static int fit_center = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int fit_end = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int fit_start = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int fit_xy = 2131034126;
			
			// aapt resource value: 0x7f050007
			public static int indicatorInside = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public static int matrix = 2131034127;
			
			// aapt resource value: 0x7f050003
			public static int numIndicator = 2131034115;
			
			// aapt resource value: 0x7f050006
			public static int numIndicatorInside = 2131034118;
			
			// aapt resource value: 0x7f050004
			public static int titleView = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int banner = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Banner = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 0
			public static int Banner_delay_time = 0;
			
			// aapt resource value: 13
			public static int Banner_image_scale_type = 13;
			
			// aapt resource value: 10
			public static int Banner_indicator_drawable_selected = 10;
			
			// aapt resource value: 11
			public static int Banner_indicator_drawable_unselected = 11;
			
			// aapt resource value: 8
			public static int Banner_indicator_height = 8;
			
			// aapt resource value: 9
			public static int Banner_indicator_margin = 9;
			
			// aapt resource value: 7
			public static int Banner_indicator_width = 7;
			
			// aapt resource value: 2
			public static int Banner_is_auto_play = 2;
			
			// aapt resource value: 12
			public static int Banner_layout_id = 12;
			
			// aapt resource value: 1
			public static int Banner_scroll_time = 1;
			
			// aapt resource value: 3
			public static int Banner_title_background = 3;
			
			// aapt resource value: 6
			public static int Banner_title_height = 6;
			
			// aapt resource value: 4
			public static int Banner_title_textcolor = 4;
			
			// aapt resource value: 5
			public static int Banner_title_textsize = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
